callofduty4x/CoD4x_Server

src/scr_vm_functions.c

Added kick with reason feature

---

src/sv_cmds.c
src/win32/sys_cod4linker_win32.c

There was 'kick all' console command in vanilla game.
#25

'kick all <reason>'

---

scriptdocumentation/script_functions_reference.md
src/scr_vm_functions.c
src/scr_vm_functions.h
src/scr_vm_main.c
src/version_build.h

Use case: displaying player's fps to other players in codjumper mod.

Added script function for getting clFPS

---

src/scr_vm_functions.c
src/scr_vm_functions.h
src/scr_vm_main.c

getSpectatorClient

---

src/sv_client.c

https://github.com/callofduty4x/CoD4x_Server/issues/158

fix ddos fake player

---

plugins/antispam/ReadMe.md
plugins/antispam/antispam_plugin.cpp
plugins/antispam/makeDLL.cmd
plugins/antispam/makeSO.sh
plugins/function_declarations.h

Hello guys. After feedback from handy people and more testing on both windows and linux,this new version fixes ALL of the bugs in the 2.3.
Now antispam also remembers yours chatban history across multiple sessions ! .
In function_declaration.h, a declaration of ```int Plugin_ClientToSlot(client_t *client);``` was missing. I added that.
Plugin tested to work fully on the current official release (2055 17.5) on both UNIX and WIN32.

Antispam Final Release

---

src_mod/phandler/dispatcher.cpp
src_mod/plugin/shared.h
src_mod/plugin/traps.h
src_plug/alltests/main.cpp

Add "Sv" functions for new plugin system

---

src/scr_vm_functions.c
src/scr_vm_functions.h
src/scr_vm_main.c

In gsx s, there is no way to calculate a number with exponent. Mostly will be usefull when the exponent is a _decimal_ number.

Add pow() function to calculate a number with exponent.

---

src/scr_vm_functions.c
src/scr_vm_functions.h
src/scr_vm_main.c

Reverts callofduty4x/CoD4x_Server#229

Revert "Added GetIP() cmd"

---

plugins/antispam/antispam_plugin.cpp
plugins/antispam/makedll.sh
plugins/antispam/makedll_win32.cmd

CHANGELOG
1- Fixed segfault when bots are added to a server
2- Check for proper playerID authentication before processing anything.
3- Fixed potentially undefined behaviour with messagecontent binary tree.
4- Fixed segfault case when a chatbanned player reconnects within the banlimit and then disconnects again.
5- Fixed memory leaks.

[Antispam Plugin] Version 2.6

---

src/g_client_fields.cpp
src/maxmind_geoip.c
src/scr_vm_functions.c
src/server.h
src/sv_client.c

addTestClient( [name] )
If name is not defined it will default to BOT, dropped support for botnames.txt

Script controlled bot names

---

src/sv_demo.c

demo recording fix

---

plugins/sourcebansplugin/makefile

Updated makefile to give correct sourcebans filename

---

plugins/function_declarations.h
src/asmsource/pluginexports.asm

Scr_AddArrayStringIndexed Plugin Support

---

src/g_client_fields.cpp
src/server.h
src/sv_client.c

Gets the language the player is using

Client field for localization

---

src/sv_bots.cpp
src/sv_bots.h
src/sv_main.c

Fixes https://github.com/callofduty4x/CoD4x_Server/issues/243

Adds botWeapon GSC Function

---

src/asmsource/_g_missile.asm
src/cscr_const.cpp
src/scr_vm.h

**Example:** 
```c
watchRocketUsage()
{
while(1)
{
self waittill( "missile_fire", rocketEntity, weaponName);
// Do stuff with rocketEntity
}
}
```

Added "rocket_fired" script event

---

src/asmsource/_g_hudelem.asm
src/scr_vm_functions.c
src/scr_vm_functions.h

I have no idea why but ``setPulseFX`` crash my server sometimes with a segfault.

HUD: SetPulseFX

---

src/sv_main.c

The original fix https://github.com/callofduty4x/CoD4x_Server/pull/336 didn't always work, this fixes it.

Fix workaround for malicious client reliableAcknowledge DOS

---

src/common_io.c
src/g_shared.h
src/g_sv_cmds.c
src/g_sv_main.c
src/qcommon_io.h
src/sv_client.c
src/sv_main.c
src/sv_snapshot.c
src/unix/sys_con_tty.c

- Changed some output printing to only print in debug (was a debug output anyway)
- Improved game-chat readability (colors depicting teams)

Console output cleanup
